; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Partition scheme for more storage if needed (optional)
; board_build.partitions = huge_app.csv

; Dependencies
lib_deps =
    fastled/FastLED @ ^3.6.0
    bblanchon/ArduinoJson @ ^6.21.3

; Build Flags
build_flags = 
    -D CORE_DEBUG_LEVEL=3       ; Info
    -D CONFIG_ARDUHAL_LOG_COLORS=1
