
export interface ManufacturerConfig {
    productName: string;
    firmwareVersion: string;

    // Hardware
    led: {
        pin: number;
        count: number;
        type: 'MATRIX' | 'STRIP'; // MATRIX might imply different mapping
        maxBrightness: number;
    };
    hasLdr: boolean;

    // Defaults
    tide: {
        defaultPortId: number; // 101=Cairu, etc.
    };
    wifi: {
        defaultSsid: string;
        defaultPass: string;
    };

    // Security
    security: {
        btPin: string;
        webPass: string;
    };
}

export class CppConfigGenerator {
    static generate(config: ManufacturerConfig): string {
        return `/**
 * AUTO-GENERATED CONFIGURATION FILE
 * Generated by TideDisplay Manufacturer App
 * Do not edit manually if using the App generator.
 */

#pragma once

// Product Identity
#define PRODUCT_NAME "${config.productName}"
#define FIRMWARE_VERSION "${config.firmwareVersion}"

// Hardware Config
#define LED_PIN ${config.led.pin}
#define NUM_LEDS ${config.led.count}
#define LED_TYPE_${config.led.type} 1
#define MAX_SAFE_BRIGHTNESS ${config.led.maxBrightness}
#define HAS_LDR ${config.hasLdr ? "1" : "0"}

// System Config
#define SERIAL_BAUD 115200
#define WATCHDOG_TIMEOUT_SEC 5
#define CRASH_THRESHOLD 3

// Tide Configuration
#define TIDE_CACHE_DAYS 30
#define TIDE_UPDATE_THRESHOLD_DAYS 5
#define TIDE_CACHE_SIZE (TIDE_CACHE_DAYS * 4)

// Default Port Chain (IDs)
#define PORT_CAIRU 101
#define PORT_VALENCA 102
#define PORT_CAMAMU 103
#define PORT_ARATU 104
#define PORT_SALVADOR 105

// Default Location Selection
#define DEFAULT_TIDE_PORT_ID ${config.tide.defaultPortId}

// WiFi Defaults (Fallback)
#define WIFI_DEFAULT_SSID "${config.wifi.defaultSsid}"
#define WIFI_DEFAULT_PASS "${config.wifi.defaultPass}"

// Security
#define BT_PAIRING_PIN "${config.security.btPin}"
#define WEB_DASHBOARD_PASS "${config.security.webPass}"
`;
    }
}
